server:
  port: 8081

spring: 
  application:
     name : authservice
     
  zipkin:
    enabled: true

  datasource: 
    url : jdbc:mysql://localhost:3306/db_fakegram_auth?useSSL=false&serverTimezone=UTC
    username : root
    password : root
  jpa: 
    properties:
      hibernate:
        dialect: ${datasource.dialect}
        connection: 
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true 
    hibernate:
      ddl-auto: none
      
keycloak:
  realm: javatechie
  auth-server-url: http://localhost:8180
  resource: springboot-keycloak
  public-client: true
  bearer-only: true